version: '3'
services:
    mongodb:
        image: mongo:3.6-xenial
        command: mongod --port 27017
        container_name: securedata-mongo
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ./dist/data:/data/db

    elasticsearch:
        environment:
            http.host: 0.0.0.0
            transport.host: 127.0.0.1
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        container_name: securedata-master-elastic
        networks:
            - securedata-ws
        ports:
            - 9200:9200
        restart: unless-stopped

    kibana:
        depends_on:
            - elasticsearch
        environment:
            ELASTICSEARCH_PASSWORD:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_USERNAME:
        image: docker.elastic.co/kibana/kibana-oss:6.6.0
        container_name: securedata-kibana
        networks:
            - securedata-ws
        ports:
            - 5601:5601
        restart: unless-stopped

# Networks to be created to facilitate communication between containers
networks:
    securedata-ws:
        driver: bridge

volumes:
  nodemodules:
    external: true
